services:
  openvpn:
    image: alekslitvinenk/openvpn
    container_name: alek-dockvpn
    volumes:
      - ./dockvpn:/opt/Dockovpn_data
    ports:
      - "1194:1194/udp"
    cap_add:
      - NET_ADMIN
    restart: always
